export const LANGS = [
  ['ru', 'RU'],
  ['en', 'EN'],
  ['zh', '中文'],
];

const tags = {
  pallet: ['24/7', '↓ LABOR', '↑ OUTPUT'],
  weld: ['QUALITY', 'REPEATABLE', 'OUTPUT'],
  move: ['AMR / AGV', '24/7', 'SCALABLE'],
  vision: ['QC', 'DETECTION', 'PRECISION'],
};

const techWords = ['INDUSTRIAL ROBOTS', 'COBOTS', 'AMR / AGV', 'MACHINE VISION', 'PLC / AUTOMATION', 'GRIPPERS', 'SAFETY SYSTEMS', 'INDUSTRIAL SOFTWARE'];

const metrics = ['CAPEX', 'OPEX', 'LABOR', 'OUTPUT', 'PAYBACK'];

export const copy = {
  ru: {
    nav: ['Решения', 'Процесс', 'Экономика', 'Контакты'],
    cta: 'Оценить операцию',
    kicker: 'INDUSTRIAL ROBOTICS INTEGRATION',
    h1: ['РОБОТИЗАЦИЯ', 'ПРОИЗВОДСТВЕННЫХ', ['ОПЕРАЦИЙ', ' ПОД КЛЮЧ']],
    heroLead: 'От оценки операции и расчёта экономики до поставки оборудования, интеграции, запуска и сервиса.',
    heroBtn: ['Пришлите видео операции', 'Получите предварительную оценку роботизации'],
    statement: ['НЕ ПРОДАЁМ РОБОТА.', 'РОБОТИЗИРУЕМ ОПЕРАЦИЮ.'],
    statementText: 'Робот — только часть системы. IROX анализирует процесс, рассчитывает экономику, подбирает оборудование и интегрирует решение в действующее производство.',
    flow: ['ПРОИЗВОДСТВЕННАЯ ЗАДАЧА', 'РАБОТАЮЩАЯ СИСТЕМА'],
    solutionsTitle: ['ЧТО МЫ', 'РОБОТИЗИРУЕМ'],
    solutions: [
      ['Роботизированное паллетирование', 'Автоматическая укладка мешков, коробок, упаковок и готовой продукции на паллеты.', tags.pallet],
      ['Роботизированная сварка', 'Роботизированные сварочные ячейки для серийного производства металлических изделий и конструкций.', tags.weld],
      ['Автономная внутренняя логистика', 'AMR / AGV для перемещения материалов, компонентов и готовой продукции между участками.', tags.move],
      ['Машинное зрение', 'Контроль качества, распознавание объектов, позиционирование и управление роботизированными операциями.', tags.vision],
    ],
    processTitle: ['ОТ ВИДЕО', 'ДО ЗАПУСКА'],
    steps: [
      ['Покажите операцию', 'Снимите короткое видео участка. Специальная подготовка и ТЗ не требуются.'],
      ['Предварительная оценка', 'Оценим потенциал роботизации и определим данные для расчёта.'],
      ['Аудит производства', 'Изучим цикл, производительность, пространство, безопасность и существующее оборудование.'],
      ['Проектирование', 'Разработаем концепцию ячейки, оснастку, управление и системы безопасности.'],
      ['Экономика', 'Рассчитаем CAPEX, OPEX, производительность, трудозатраты и окупаемость.'],
      ['Интеграция и запуск', 'Поставка, монтаж, программирование, пусконаладка, обучение и сервис.'],
    ],
    econ: { before: ['СНАЧАЛА'], accent: 'СЧИТАЕМ.', after: ['ПОТОМ', 'ВНЕДРЯЕМ.'] },
    econText: 'Роботизация должна иметь понятный экономический эффект. Для каждого проекта оцениваем ключевые параметры.',
    metrics: ['Инвестиции в оборудование и интеграцию', 'Эксплуатационные расходы', 'Изменение трудозатрат', 'Производительность', 'Расчётный срок окупаемости'],
    tech: { before: 'THE ROBOT IS', accent: 'ONLY ONE PART.' },
    techWords,
    leadTitle: ['ПРИШЛИТЕ', 'ВИДЕО ОПЕРАЦИИ'],
    leadSub: 'Получите предварительную оценку роботизации',
    leadText: 'Не нужно составлять техническое задание. Снимите на телефон операцию, которую хотите автоматизировать.',
    leadList: ['Можно ли её роботизировать', 'Какой тип решения может подойти', 'Какие данные нужны для расчёта', 'Есть ли смысл переходить к аудиту'],
    fields: [
      ['ИМЯ', 'Александр', 'text'],
      ['КОМПАНИЯ', 'Название компании', 'text'],
      ['ТЕЛЕФОН / TELEGRAM', '+7 999 000-00-00', 'text'],
      ['E-MAIL', 'name@company.ru', 'email'],
    ],
    about: ['ЧТО ХОТИТЕ РОБОТИЗИРОВАТЬ?', 'Коротко опишите операцию'],
    upload: ['ПРИКРЕПИТЬ ВИДЕО', 'MP4, MOV — до 100 МБ'],
    submit: 'ПОЛУЧИТЬ ПРЕДВАРИТЕЛЬНУЮ ОЦЕНКУ',
    privacy: 'Отправляя данные, вы соглашаетесь с политикой обработки персональных данных.',
    footer: 'Роботизация производственных операций под ключ.',
  },
  en: {
    nav: ['Solutions', 'Process', 'Economics', 'Contact'],
    cta: 'Assess an operation',
    kicker: 'INDUSTRIAL ROBOTICS INTEGRATION',
    h1: ['ROBOTIZING', 'PRODUCTION', ['OPERATIONS', ' TURNKEY']],
    heroLead: 'From assessing the operation and the business case to equipment supply, integration, launch and service.',
    heroBtn: ['Send a video of the operation', 'Get a preliminary robotization assessment'],
    statement: ["WE DON'T SELL A ROBOT.", 'WE ROBOTIZE THE OPERATION.'],
    statementText: 'A robot is only part of the system. IROX analyzes the process, calculates the economics, selects the equipment and integrates the solution into a running plant.',
    flow: ['PRODUCTION TASK', 'WORKING SYSTEM'],
    solutionsTitle: ['WHAT WE', 'ROBOTIZE'],
    solutions: [
      ['Robotic palletizing', 'Automatic stacking of bags, boxes, packs and finished goods onto pallets.', tags.pallet],
      ['Robotic welding', 'Robotic welding cells for serial production of metal parts and structures.', tags.weld],
      ['Autonomous in-plant logistics', 'AMR / AGV move materials, components and finished goods between areas.', tags.move],
      ['Machine vision', 'Quality control, object detection, positioning and control of robotic operations.', tags.vision],
    ],
    processTitle: ['FROM A VIDEO', 'TO LAUNCH'],
    steps: [
      ['Show the operation', 'Film a short clip of the area. No special preparation or specification is required.'],
      ['Preliminary assessment', 'We estimate the robotization potential and define the data needed for the calculation.'],
      ['Plant audit', 'We study cycle time, throughput, space, safety and the existing equipment.'],
      ['Engineering', 'We design the cell concept, tooling, controls and safety systems.'],
      ['Economics', 'We calculate CAPEX, OPEX, throughput, labor and payback.'],
      ['Integration and launch', 'Supply, installation, programming, commissioning, training and service.'],
    ],
    econ: { before: ['FIRST'], accent: 'WE COUNT.', after: ['THEN', 'WE DEPLOY.'] },
    econText: 'Robotization has to show a clear economic effect. For every project we estimate the key parameters.',
    metrics: ['Investment in equipment and integration', 'Operating costs', 'Change in labor', 'Throughput', 'Estimated payback'],
    tech: { before: 'THE ROBOT IS', accent: 'ONLY ONE PART.' },
    techWords,
    leadTitle: ['SEND A VIDEO', 'OF THE OPERATION'],
    leadSub: 'Get a preliminary robotization assessment',
    leadText: 'No specification required. Film the operation you want to automate on your phone.',
    leadList: ['Whether it can be robotized', 'What type of solution may fit', 'What data the calculation needs', 'Whether an audit is worth doing'],
    fields: [
      ['NAME', 'Alex', 'text'],
      ['COMPANY', 'Company name', 'text'],
      ['PHONE / TELEGRAM', '+7 999 000-00-00', 'text'],
      ['E-MAIL', 'name@company.com', 'email'],
    ],
    about: ['WHAT DO YOU WANT TO ROBOTIZE?', 'Briefly describe the operation'],
    upload: ['ATTACH A VIDEO', 'MP4, MOV — up to 100 MB'],
    submit: 'GET A PRELIMINARY ASSESSMENT',
    privacy: 'By sending this data you agree to the personal data policy.',
    footer: 'Turnkey robotization of production operations.',
  },
  zh: {
    nav: ['方案', '流程', '经济性', '联系'],
    cta: '评估作业',
    kicker: 'INDUSTRIAL ROBOTICS INTEGRATION',
    h1: ['生产作业', '机器人化', ['交钥匙', '交付']],
    heroLead: '从作业评估和经济效益测算，到设备供应、集成、投产与服务。',
    heroBtn: ['发送作业视频', '获取机器人化初步评估'],
    statement: ['我们不卖机器人。', '我们把作业机器人化。'],
    statementText: '机器人只是系统的一部分。IROX 分析流程、测算经济性、选型设备，并把方案集成到现有生产中。',
    flow: ['生产任务', '可运行的系统'],
    solutionsTitle: ['我们实现', '哪些机器人化'],
    solutions: [
      ['机器人码垛', '自动将袋装、箱装、包装及成品码放到托盘上。', tags.pallet],
      ['机器人焊接', '面向金属制品与结构件批量生产的机器人焊接单元。', tags.weld],
      ['厂内自主物流', '用 AMR / AGV 在工位之间运送物料、零部件和成品。', tags.move],
      ['机器视觉', '质量检测、目标识别、定位，并控制机器人作业。', tags.vision],
    ],
    processTitle: ['从视频', '到投产'],
    steps: [
      ['拍下作业', '用手机拍一段工位短视频。不需要专门准备，也不用写技术任务书。'],
      ['初步评估', '评估机器人化潜力，并确定测算所需的数据。'],
      ['生产审计', '研究节拍、产能、空间、安全和现有设备。'],
      ['工程设计', '设计单元方案、工装、控制和安全系统。'],
      ['经济性', '计算 CAPEX、OPEX、产能、人工和回收期。'],
      ['集成与投产', '供货、安装、编程、调试、培训和服务。'],
    ],
    econ: { before: ['先算清楚。'], accent: '再去实施。', after: [] },
    econText: '机器人化必须有清楚的经济效益。每个项目我们都评估这些关键参数。',
    metrics: ['设备与集成投资', '运营成本', '人工变化', '产能', '预计回收期'],
    tech: { before: '机器人', accent: '只是一部分。' },
    techWords,
    leadTitle: ['发来', '作业视频'],
    leadSub: '获取机器人化初步评估',
    leadText: '不必编写技术任务书。用手机拍下你想自动化的作业。',
    leadList: ['能否机器人化', '可能适合哪类方案', '测算还需要哪些数据', '是否有必要进入审计'],
    fields: [
      ['姓名', '李明', 'text'],
      ['公司', '公司名称', 'text'],
      ['电话 / TELEGRAM', '+86 000 0000 0000', 'text'],
      ['邮箱', 'name@company.cn', 'email'],
    ],
    about: ['想把什么机器人化？', '简要描述这项作业'],
    upload: ['附上视频', 'MP4、MOV — 不超过 100 MB'],
    submit: '获取初步评估',
    privacy: '提交数据即表示你同意个人数据处理政策。',
    footer: '生产作业交钥匙机器人化。',
  },
};

export const solutionMeta = [
  ['01', 'PALLET'],
  ['02', 'WELD'],
  ['03', 'MOVE'],
  ['04', 'VISION'],
];

export const stepMeta = ['VIDEO', 'ANALYSIS', 'AUDIT', 'ENGINEERING', 'ECONOMICS', 'INTEGRATION'];

export { metrics };
