'use client';
import {ArrowUpRight,Upload,Menu,X,ScanLine,Bot,Truck,Flame,ChevronRight} from 'lucide-react';
import {useState} from 'react';
const solutions=[
 {code:'01',name:'PALLET',title:'Роботизированное паллетирование',text:'Автоматическая укладка мешков, коробок, упаковок и готовой продукции на паллеты.',icon:Bot,tags:['24/7','↓ LABOR','↑ OUTPUT']},
 {code:'02',name:'WELD',title:'Роботизированная сварка',text:'Роботизированные сварочные ячейки для серийного производства металлических изделий и конструкций.',icon:Flame,tags:['QUALITY','REPEATABLE','OUTPUT']},
 {code:'03',name:'MOVE',title:'Автономная внутренняя логистика',text:'AMR / AGV для перемещения материалов, компонентов и готовой продукции между участками.',icon:Truck,tags:['AMR / AGV','24/7','SCALABLE']},
 {code:'04',name:'VISION',title:'Машинное зрение',text:'Контроль качества, распознавание объектов, позиционирование и управление роботизированными операциями.',icon:ScanLine,tags:['QC','DETECTION','PRECISION']}
];
const steps=[['01','VIDEO','Покажите операцию','Снимите короткое видео участка. Специальная подготовка и ТЗ не требуются.'],['02','ANALYSIS','Предварительная оценка','Оценим потенциал роботизации и определим данные для расчёта.'],['03','AUDIT','Аудит производства','Изучим цикл, производительность, пространство, безопасность и существующее оборудование.'],['04','ENGINEERING','Проектирование','Разработаем концепцию ячейки, оснастку, управление и системы безопасности.'],['05','ECONOMICS','Экономика','Рассчитаем CAPEX, OPEX, производительность, трудозатраты и окупаемость.'],['06','INTEGRATION','Интеграция и запуск','Поставка, монтаж, программирование, пусконаладка, обучение и сервис.']];
function Logo(){return <a className="logo" href="#" aria-label="IROX"><svg width="28" height="16" viewBox="0 0 28 16" aria-hidden="true"><path d="M1 1.5h7M1 1.5v13M1 14.5h7M27 1.5h-7M27 1.5v13M27 14.5h-7M11.5 8h5" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="square"/></svg><b>IROX</b></a>}
function Header(){const [open,setOpen]=useState(false);return <header><Logo/><nav className={open?'open':''}><a href="#solutions" onClick={()=>setOpen(false)}>Решения</a><a href="#process" onClick={()=>setOpen(false)}>Процесс</a><a href="#economics" onClick={()=>setOpen(false)}>Экономика</a><a href="#contact" onClick={()=>setOpen(false)}>Контакты</a></nav><a className="headerCta" href="#lead">Оценить операцию <ArrowUpRight size={16}/></a><button className="menu" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></header>}
export default function Home(){return <main><Header/>
<section className="hero"><div className="gridbg"/><div className="eyebrow">INDUSTRIAL ROBOTICS INTEGRATION <span>2026</span></div><h1>РОБОТИЗАЦИЯ<br/>ПРОИЗВОДСТВЕННЫХ<br/><em>ОПЕРАЦИЙ</em> ПОД КЛЮЧ</h1><div className="heroBottom"><p>От оценки операции и расчёта экономики до поставки оборудования, интеграции, запуска и сервиса.</p><a className="primary" href="#lead"><span>Пришлите видео операции</span><b>Получите предварительную оценку роботизации</b><ArrowUpRight/></a></div><div className="ticker"><span>PALLET</span><i/> <span>WELD</span><i/> <span>MOVE</span><i/> <span>VISION</span></div></section>
<section className="statement"><div className="sectionNo">01 / APPROACH</div><h2>НЕ ПРОДАЁМ РОБОТА.<br/><span>РОБОТИЗИРУЕМ ОПЕРАЦИЮ.</span></h2><div className="statementText"><p>Робот — только часть системы. IROX анализирует процесс, рассчитывает экономику, подбирает оборудование и интегрирует решение в действующее производство.</p><div className="flow">ПРОИЗВОДСТВЕННАЯ ЗАДАЧА <ChevronRight/> <strong>РАБОТАЮЩАЯ СИСТЕМА</strong></div></div></section>
<section id="solutions" className="solutions"><div className="sectionHead"><div className="sectionNo">02 / SOLUTIONS</div><h2>ЧТО МЫ<br/>РОБОТИЗИРУЕМ</h2></div><div className="solutionGrid">{solutions.map(({code,name,title,text,icon:Icon,tags})=><article className="solution" key={name}><div className="cardTop"><span>{code}</span><Icon size={32}/></div><h3>IROX <b>{name}</b></h3><h4>{title}</h4><p>{text}</p><div className="tags">{tags.map(t=><span key={t}>{t}</span>)}</div></article>)}</div></section>
<section id="process" className="process"><div className="sectionHead light"><div className="sectionNo">03 / FROM OPERATION TO AUTOMATION</div><h2>ОТ ВИДЕО<br/>ДО ЗАПУСКА</h2></div><div className="steps">{steps.map(s=><div className="step" key={s[0]}><div className="stepNum">{s[0]}</div><div><small>{s[1]}</small><h3>{s[2]}</h3><p>{s[3]}</p></div></div>)}</div></section>
<section id="economics" className="economics"><div className="sectionNo">04 / BUSINESS CASE</div><div className="econGrid"><div><h2>СНАЧАЛА<br/><span>СЧИТАЕМ.</span><br/>ПОТОМ<br/>ВНЕДРЯЕМ.</h2></div><div className="metrics"><p>Роботизация должна иметь понятный экономический эффект. Для каждого проекта оцениваем ключевые параметры.</p>{[['CAPEX','Инвестиции в оборудование и интеграцию'],['OPEX','Эксплуатационные расходы'],['LABOR','Изменение трудозатрат'],['OUTPUT','Производительность'],['PAYBACK','Расчётный срок окупаемости']].map(m=><div className="metric" key={m[0]}><b>{m[0]}</b><span>{m[1]}</span></div>)}</div></div></section>
<section className="tech"><div className="sectionNo">05 / TECHNOLOGY</div><h2>THE ROBOT IS<br/><span>ONLY ONE PART.</span></h2><div className="techWords">{['INDUSTRIAL ROBOTS','COBOTS','AMR / AGV','MACHINE VISION','PLC / AUTOMATION','GRIPPERS','SAFETY SYSTEMS','INDUSTRIAL SOFTWARE'].map(x=><span key={x}>{x}</span>)}</div></section>
<section id="lead" className="lead"><div className="leadCopy"><div className="sectionNo">06 / START WITH A VIDEO</div><h2>ПРИШЛИТЕ<br/>ВИДЕО ОПЕРАЦИИ</h2><h3>Получите предварительную оценку роботизации</h3><p>Не нужно составлять техническое задание. Снимите на телефон операцию, которую хотите автоматизировать.</p><ol><li>Можно ли её роботизировать</li><li>Какой тип решения может подойти</li><li>Какие данные нужны для расчёта</li><li>Есть ли смысл переходить к аудиту</li></ol></div><form onSubmit={e=>e.preventDefault()}><label>ИМЯ<input placeholder="Александр"/></label><label>КОМПАНИЯ<input placeholder="Название компании"/></label><label>ТЕЛЕФОН / TELEGRAM<input placeholder="+7 999 000-00-00"/></label><label>E-MAIL<input type="email" placeholder="name@company.ru"/></label><label>ЧТО ХОТИТЕ РОБОТИЗИРОВАТЬ?<textarea placeholder="Коротко опишите операцию"/></label><label className="upload"><Upload/><span><b>ПРИКРЕПИТЬ ВИДЕО</b><small>MP4, MOV — до 100 МБ</small></span><input type="file" accept="video/*"/></label><button type="submit">ПОЛУЧИТЬ ПРЕДВАРИТЕЛЬНУЮ ОЦЕНКУ <ArrowUpRight/></button><small className="privacy">Отправляя данные, вы соглашаетесь с политикой обработки персональных данных.</small></form></section>
<footer id="contact"><Logo/><div><b>PALLET · WELD · MOVE · VISION</b><p>Роботизация производственных операций под ключ.</p></div><div className="footerRight"><a href="mailto:hello@irox.ru">hello@irox.ru</a><span>© 2026 IROX</span></div></footer>
</main>}
